package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CaafDrawdownendId generated by hbm2java
 */
@Embeddable
public class CaafDrawdownendId implements java.io.Serializable {

	private int permnoEnd;
	private int yrmoEnd;

	public CaafDrawdownendId() {
	}

	public CaafDrawdownendId(int permnoEnd, int yrmoEnd) {
		this.permnoEnd = permnoEnd;
		this.yrmoEnd = yrmoEnd;
	}

	@Column(name = "permno_end", nullable = false)
	public int getPermnoEnd() {
		return this.permnoEnd;
	}

	public void setPermnoEnd(int permnoEnd) {
		this.permnoEnd = permnoEnd;
	}

	@Column(name = "yrmo_end", nullable = false)
	public int getYrmoEnd() {
		return this.yrmoEnd;
	}

	public void setYrmoEnd(int yrmoEnd) {
		this.yrmoEnd = yrmoEnd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaafDrawdownendId))
			return false;
		CaafDrawdownendId castOther = (CaafDrawdownendId) other;

		return (this.getPermnoEnd() == castOther.getPermnoEnd())
				&& (this.getYrmoEnd() == castOther.getYrmoEnd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermnoEnd();
		result = 37 * result + this.getYrmoEnd();
		return result;
	}

}
