package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaafDrawdownend generated by hbm2java
 */
@Entity
@Table(name = "caaf_drawdownend", catalog = "karsha_drawdowns")
public class CaafDrawdownend implements java.io.Serializable {

	private CaafDrawdownendId id;
	private Date dateWithyear;
	private String value2;
	private String value3;
	private String value6;
	private String value24;

	public CaafDrawdownend() {
	}

	public CaafDrawdownend(CaafDrawdownendId id) {
		this.id = id;
	}

	public CaafDrawdownend(CaafDrawdownendId id, Date dateWithyear,
			String value2, String value3, String value6, String value24) {
		this.id = id;
		this.dateWithyear = dateWithyear;
		this.value2 = value2;
		this.value3 = value3;
		this.value6 = value6;
		this.value24 = value24;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permnoEnd", column = @Column(name = "permno_end", nullable = false)),
			@AttributeOverride(name = "yrmoEnd", column = @Column(name = "yrmo_end", nullable = false)) })
	public CaafDrawdownendId getId() {
		return this.id;
	}

	public void setId(CaafDrawdownendId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_withyear", length = 10)
	public Date getDateWithyear() {
		return this.dateWithyear;
	}

	public void setDateWithyear(Date dateWithyear) {
		this.dateWithyear = dateWithyear;
	}

	@Column(name = "value2", length = 10)
	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	@Column(name = "value3", length = 10)
	public String getValue3() {
		return this.value3;
	}

	public void setValue3(String value3) {
		this.value3 = value3;
	}

	@Column(name = "value6", length = 10)
	public String getValue6() {
		return this.value6;
	}

	public void setValue6(String value6) {
		this.value6 = value6;
	}

	@Column(name = "value24", length = 10)
	public String getValue24() {
		return this.value24;
	}

	public void setValue24(String value24) {
		this.value24 = value24;
	}

}
