package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CaafMarketcapitalization generated by hbm2java
 */
@Entity
@Table(name = "caaf_marketcapitalization", catalog = "capm_db")
public class CaafMarketcapitalization implements java.io.Serializable {

	private CaafMarketcapitalizationId id;
	private String value1;
	private String value2;
	private String value3;
	private String value6;
	private String value24;

	public CaafMarketcapitalization() {
	}

	public CaafMarketcapitalization(CaafMarketcapitalizationId id) {
		this.id = id;
	}

	public CaafMarketcapitalization(CaafMarketcapitalizationId id,
			String value1, String value2, String value3, String value6,
			String value24) {
		this.id = id;
		this.value1 = value1;
		this.value2 = value2;
		this.value3 = value3;
		this.value6 = value6;
		this.value24 = value24;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permno", column = @Column(name = "permno", nullable = false)),
			@AttributeOverride(name = "yrmo", column = @Column(name = "yrmo", nullable = false)) })
	public CaafMarketcapitalizationId getId() {
		return this.id;
	}

	public void setId(CaafMarketcapitalizationId id) {
		this.id = id;
	}

	@Column(name = "value1", length = 11)
	public String getValue1() {
		return this.value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	@Column(name = "value2", length = 11)
	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	@Column(name = "value3", length = 10)
	public String getValue3() {
		return this.value3;
	}

	public void setValue3(String value3) {
		this.value3 = value3;
	}

	@Column(name = "value6", length = 10)
	public String getValue6() {
		return this.value6;
	}

	public void setValue6(String value6) {
		this.value6 = value6;
	}

	@Column(name = "value24", length = 10)
	public String getValue24() {
		return this.value24;
	}

	public void setValue24(String value24) {
		this.value24 = value24;
	}

}
