package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CapmPttStartDatesId generated by hbm2java
 */
@Embeddable
public class CapmPttStartDatesId implements java.io.Serializable {

	private Integer permno;
	private Integer yrmo;
	private Integer horizon;
	private String value0;
	private String value1;
	private String value2;

	public CapmPttStartDatesId() {
	}

	public CapmPttStartDatesId(Integer permno, Integer yrmo, Integer horizon,
			String value0, String value1, String value2) {
		this.permno = permno;
		this.yrmo = yrmo;
		this.horizon = horizon;
		this.value0 = value0;
		this.value1 = value1;
		this.value2 = value2;
	}

	@Column(name = "PERMNO")
	public Integer getPermno() {
		return this.permno;
	}

	public void setPermno(Integer permno) {
		this.permno = permno;
	}

	@Column(name = "YRMO")
	public Integer getYrmo() {
		return this.yrmo;
	}

	public void setYrmo(Integer yrmo) {
		this.yrmo = yrmo;
	}

	@Column(name = "HORIZON")
	public Integer getHorizon() {
		return this.horizon;
	}

	public void setHorizon(Integer horizon) {
		this.horizon = horizon;
	}

	@Column(name = "value0", length = 10)
	public String getValue0() {
		return this.value0;
	}

	public void setValue0(String value0) {
		this.value0 = value0;
	}

	@Column(name = "value1", length = 10)
	public String getValue1() {
		return this.value1;
	}

	public void setValue1(String value1) {
		this.value1 = value1;
	}

	@Column(name = "value2", length = 10)
	public String getValue2() {
		return this.value2;
	}

	public void setValue2(String value2) {
		this.value2 = value2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CapmPttStartDatesId))
			return false;
		CapmPttStartDatesId castOther = (CapmPttStartDatesId) other;

		return ((this.getPermno() == castOther.getPermno()) || (this
				.getPermno() != null && castOther.getPermno() != null && this
				.getPermno().equals(castOther.getPermno())))
				&& ((this.getYrmo() == castOther.getYrmo()) || (this.getYrmo() != null
						&& castOther.getYrmo() != null && this.getYrmo()
						.equals(castOther.getYrmo())))
				&& ((this.getHorizon() == castOther.getHorizon()) || (this
						.getHorizon() != null && castOther.getHorizon() != null && this
						.getHorizon().equals(castOther.getHorizon())))
				&& ((this.getValue0() == castOther.getValue0()) || (this
						.getValue0() != null && castOther.getValue0() != null && this
						.getValue0().equals(castOther.getValue0())))
				&& ((this.getValue1() == castOther.getValue1()) || (this
						.getValue1() != null && castOther.getValue1() != null && this
						.getValue1().equals(castOther.getValue1())))
				&& ((this.getValue2() == castOther.getValue2()) || (this
						.getValue2() != null && castOther.getValue2() != null && this
						.getValue2().equals(castOther.getValue2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPermno() == null ? 0 : this.getPermno().hashCode());
		result = 37 * result
				+ (getYrmo() == null ? 0 : this.getYrmo().hashCode());
		result = 37 * result
				+ (getHorizon() == null ? 0 : this.getHorizon().hashCode());
		result = 37 * result
				+ (getValue0() == null ? 0 : this.getValue0().hashCode());
		result = 37 * result
				+ (getValue1() == null ? 0 : this.getValue1().hashCode());
		result = 37 * result
				+ (getValue2() == null ? 0 : this.getValue2().hashCode());
		return result;
	}

}
