package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CapmDrawdownsResultsId generated by hbm2java
 */
@Embeddable
public class CapmDrawdownsResultsId implements java.io.Serializable {

	private int permno;
	private int yrmo;
	private int horizon;

	public CapmDrawdownsResultsId() {
	}

	public CapmDrawdownsResultsId(int permno, int yrmo, int horizon) {
		this.permno = permno;
		this.yrmo = yrmo;
		this.horizon = horizon;
	}

	@Column(name = "PERMNO", nullable = false)
	public int getPermno() {
		return this.permno;
	}

	public void setPermno(int permno) {
		this.permno = permno;
	}

	@Column(name = "YRMO", nullable = false)
	public int getYrmo() {
		return this.yrmo;
	}

	public void setYrmo(int yrmo) {
		this.yrmo = yrmo;
	}

	@Column(name = "HORIZON", nullable = false)
	public int getHorizon() {
		return this.horizon;
	}

	public void setHorizon(int horizon) {
		this.horizon = horizon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CapmDrawdownsResultsId))
			return false;
		CapmDrawdownsResultsId castOther = (CapmDrawdownsResultsId) other;

		return (this.getPermno() == castOther.getPermno())
				&& (this.getYrmo() == castOther.getYrmo())
				&& (this.getHorizon() == castOther.getHorizon());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermno();
		result = 37 * result + this.getYrmo();
		result = 37 * result + this.getHorizon();
		return result;
	}

}
