package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CapmPttResults generated by hbm2java
 */
@Entity
@Table(name = "capm_ptt_results", catalog = "karsha_drawdowns")
public class CapmPttResults implements java.io.Serializable {

	private CapmPttResultsId id;

	public CapmPttResults() {
	}

	public CapmPttResults(CapmPttResultsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permno", column = @Column(name = "PERMNO")),
			@AttributeOverride(name = "yrmo", column = @Column(name = "YRMO")),
			@AttributeOverride(name = "horizon", column = @Column(name = "HORIZON")),
			@AttributeOverride(name = "ret", column = @Column(name = "RET", precision = 11, scale = 9)),
			@AttributeOverride(name = "capmResid", column = @Column(name = "CAPM_resid", precision = 11, scale = 9)),
			@AttributeOverride(name = "ff3Resid", column = @Column(name = "FF3_resid", precision = 11, scale = 9)) })
	public CapmPttResultsId getId() {
		return this.id;
	}

	public void setId(CapmPttResultsId id) {
		this.id = id;
	}

}
