package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CapmDrawdownsResults generated by hbm2java
 */
@Entity
@Table(name = "capm_drawdowns_results", catalog = "karsha_drawdowns")
public class CapmDrawdownsResults implements java.io.Serializable {

	private CapmDrawdownsResultsId id;
	private BigDecimal ret;
	private BigDecimal capmResid;
	private BigDecimal ff3Resid;

	public CapmDrawdownsResults() {
	}

	public CapmDrawdownsResults(CapmDrawdownsResultsId id) {
		this.id = id;
	}

	public CapmDrawdownsResults(CapmDrawdownsResultsId id, BigDecimal ret,
			BigDecimal capmResid, BigDecimal ff3Resid) {
		this.id = id;
		this.ret = ret;
		this.capmResid = capmResid;
		this.ff3Resid = ff3Resid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permno", column = @Column(name = "PERMNO", nullable = false)),
			@AttributeOverride(name = "yrmo", column = @Column(name = "YRMO", nullable = false)),
			@AttributeOverride(name = "horizon", column = @Column(name = "HORIZON", nullable = false)) })
	public CapmDrawdownsResultsId getId() {
		return this.id;
	}

	public void setId(CapmDrawdownsResultsId id) {
		this.id = id;
	}

	@Column(name = "RET", precision = 11, scale = 9)
	public BigDecimal getRet() {
		return this.ret;
	}

	public void setRet(BigDecimal ret) {
		this.ret = ret;
	}

	@Column(name = "CAPM_resid", precision = 11, scale = 9)
	public BigDecimal getCapmResid() {
		return this.capmResid;
	}

	public void setCapmResid(BigDecimal capmResid) {
		this.capmResid = capmResid;
	}

	@Column(name = "FF3_resid", precision = 11, scale = 9)
	public BigDecimal getFf3Resid() {
		return this.ff3Resid;
	}

	public void setFf3Resid(BigDecimal ff3Resid) {
		this.ff3Resid = ff3Resid;
	}

}
