package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CapmDrawdownsDate generated by hbm2java
 */
@Entity
@Table(name = "capm_drawdowns_date", catalog = "karsha_drawdowns")
public class CapmDrawdownsDate implements java.io.Serializable {

	private CapmDrawdownsDateId id;
	private String ret;
	private String capmResidDate;
	private String ff3Resid;

	public CapmDrawdownsDate() {
	}

	public CapmDrawdownsDate(CapmDrawdownsDateId id) {
		this.id = id;
	}

	public CapmDrawdownsDate(CapmDrawdownsDateId id, String ret,
			String capmResidDate, String ff3Resid) {
		this.id = id;
		this.ret = ret;
		this.capmResidDate = capmResidDate;
		this.ff3Resid = ff3Resid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permnoDate", column = @Column(name = "PERMNO_date", nullable = false)),
			@AttributeOverride(name = "yrmoDate", column = @Column(name = "YRMO_date", nullable = false)),
			@AttributeOverride(name = "horizon", column = @Column(name = "HORIZON", nullable = false)) })
	public CapmDrawdownsDateId getId() {
		return this.id;
	}

	public void setId(CapmDrawdownsDateId id) {
		this.id = id;
	}

	@Column(name = "RET", length = 10)
	public String getRet() {
		return this.ret;
	}

	public void setRet(String ret) {
		this.ret = ret;
	}

	@Column(name = "CAPM_resid_date", length = 10)
	public String getCapmResidDate() {
		return this.capmResidDate;
	}

	public void setCapmResidDate(String capmResidDate) {
		this.capmResidDate = capmResidDate;
	}

	@Column(name = "FF3_resid", length = 10)
	public String getFf3Resid() {
		return this.ff3Resid;
	}

	public void setFf3Resid(String ff3Resid) {
		this.ff3Resid = ff3Resid;
	}

}
