package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CapmPttResultsId generated by hbm2java
 */
@Embeddable
public class CapmPttResultsId implements java.io.Serializable {

	private Integer permno;
	private Integer yrmo;
	private Integer horizon;
	private BigDecimal ret;
	private BigDecimal capmResid;
	private BigDecimal ff3Resid;

	public CapmPttResultsId() {
	}

	public CapmPttResultsId(Integer permno, Integer yrmo, Integer horizon,
			BigDecimal ret, BigDecimal capmResid, BigDecimal ff3Resid) {
		this.permno = permno;
		this.yrmo = yrmo;
		this.horizon = horizon;
		this.ret = ret;
		this.capmResid = capmResid;
		this.ff3Resid = ff3Resid;
	}

	@Column(name = "PERMNO")
	public Integer getPermno() {
		return this.permno;
	}

	public void setPermno(Integer permno) {
		this.permno = permno;
	}

	@Column(name = "YRMO")
	public Integer getYrmo() {
		return this.yrmo;
	}

	public void setYrmo(Integer yrmo) {
		this.yrmo = yrmo;
	}

	@Column(name = "HORIZON")
	public Integer getHorizon() {
		return this.horizon;
	}

	public void setHorizon(Integer horizon) {
		this.horizon = horizon;
	}

	@Column(name = "RET", precision = 11, scale = 9)
	public BigDecimal getRet() {
		return this.ret;
	}

	public void setRet(BigDecimal ret) {
		this.ret = ret;
	}

	@Column(name = "CAPM_resid", precision = 11, scale = 9)
	public BigDecimal getCapmResid() {
		return this.capmResid;
	}

	public void setCapmResid(BigDecimal capmResid) {
		this.capmResid = capmResid;
	}

	@Column(name = "FF3_resid", precision = 11, scale = 9)
	public BigDecimal getFf3Resid() {
		return this.ff3Resid;
	}

	public void setFf3Resid(BigDecimal ff3Resid) {
		this.ff3Resid = ff3Resid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CapmPttResultsId))
			return false;
		CapmPttResultsId castOther = (CapmPttResultsId) other;

		return ((this.getPermno() == castOther.getPermno()) || (this
				.getPermno() != null && castOther.getPermno() != null && this
				.getPermno().equals(castOther.getPermno())))
				&& ((this.getYrmo() == castOther.getYrmo()) || (this.getYrmo() != null
						&& castOther.getYrmo() != null && this.getYrmo()
						.equals(castOther.getYrmo())))
				&& ((this.getHorizon() == castOther.getHorizon()) || (this
						.getHorizon() != null && castOther.getHorizon() != null && this
						.getHorizon().equals(castOther.getHorizon())))
				&& ((this.getRet() == castOther.getRet()) || (this.getRet() != null
						&& castOther.getRet() != null && this.getRet().equals(
						castOther.getRet())))
				&& ((this.getCapmResid() == castOther.getCapmResid()) || (this
						.getCapmResid() != null
						&& castOther.getCapmResid() != null && this
						.getCapmResid().equals(castOther.getCapmResid())))
				&& ((this.getFf3Resid() == castOther.getFf3Resid()) || (this
						.getFf3Resid() != null
						&& castOther.getFf3Resid() != null && this
						.getFf3Resid().equals(castOther.getFf3Resid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPermno() == null ? 0 : this.getPermno().hashCode());
		result = 37 * result
				+ (getYrmo() == null ? 0 : this.getYrmo().hashCode());
		result = 37 * result
				+ (getHorizon() == null ? 0 : this.getHorizon().hashCode());
		result = 37 * result
				+ (getRet() == null ? 0 : this.getRet().hashCode());
		result = 37 * result
				+ (getCapmResid() == null ? 0 : this.getCapmResid().hashCode());
		result = 37 * result
				+ (getFf3Resid() == null ? 0 : this.getFf3Resid().hashCode());
		return result;
	}

}
