package model;

// Generated Nov 16, 2015 2:20:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CapmDrawdownsDateId generated by hbm2java
 */
@Embeddable
public class CapmDrawdownsDateId implements java.io.Serializable {

	private int permnoDate;
	private int yrmoDate;
	private int horizon;

	public CapmDrawdownsDateId() {
	}

	public CapmDrawdownsDateId(int permnoDate, int yrmoDate, int horizon) {
		this.permnoDate = permnoDate;
		this.yrmoDate = yrmoDate;
		this.horizon = horizon;
	}

	@Column(name = "PERMNO_date", nullable = false)
	public int getPermnoDate() {
		return this.permnoDate;
	}

	public void setPermnoDate(int permnoDate) {
		this.permnoDate = permnoDate;
	}

	@Column(name = "YRMO_date", nullable = false)
	public int getYrmoDate() {
		return this.yrmoDate;
	}

	public void setYrmoDate(int yrmoDate) {
		this.yrmoDate = yrmoDate;
	}

	@Column(name = "HORIZON", nullable = false)
	public int getHorizon() {
		return this.horizon;
	}

	public void setHorizon(int horizon) {
		this.horizon = horizon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CapmDrawdownsDateId))
			return false;
		CapmDrawdownsDateId castOther = (CapmDrawdownsDateId) other;

		return (this.getPermnoDate() == castOther.getPermnoDate())
				&& (this.getYrmoDate() == castOther.getYrmoDate())
				&& (this.getHorizon() == castOther.getHorizon());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPermnoDate();
		result = 37 * result + this.getYrmoDate();
		result = 37 * result + this.getHorizon();
		return result;
	}

}
